### ISSUE TITLE
This version of the ONNX parser only supports TensorRT INetworkDefinitions with an explicit batch dimension

### ISSUE THREAD

**Issue by demuxin** [NVIDIA/TensorRT-Model-Optimizer#111]
I want to quantize onnx  model, and I use the  command  below:
```
moq.quantize(
    onnx_path = onnx_path,
    quantize_mode = "int8",
    calibration_data = calibration_data,
    output_path = quant_path,
    verbose = True,
)
```

output some error  message : 
```
[12/09/2024-17:47:09] [TRT] [W] The implicit batch dimension mode has been deprecated. Please create the network with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag whenever possible.
Traceback (most recent call last):
  File "/media/yin/Data/workspace/KLAlgorithmWheel/auto_script/trt_model_opt.py", line 60, in <module>
    moq.quantize(
  File "/media/yin/Data/anaconda3/envs/pytorch/lib/python3.9/site-packages/modelopt/onnx/quantization/quantize.py", line 269, in quantize
    onnx_path, intermediate_generated_files, has_custom_op = _preprocess_onnx(
  File "/media/yin/Data/anaconda3/envs/pytorch/lib/python3.9/site-packages/modelopt/onnx/quantization/quantize.py", line 77, in _preprocess_onnx
    onnx_model, has_custom_op, custom_ops = load_onnx_model(
  File "/media/yin/Data/anaconda3/envs/pytorch/lib/python3.9/site-packages/modelopt/onnx/quantization/trt_utils.py", line 95, in load_onnx_model
    custom_layers = get_custom_layers(onnx_path, trt_plugins)
  File "/media/yin/Data/anaconda3/envs/pytorch/lib/python3.9/site-packages/modelopt/onnx/quantization/trt_utils.py", line 56, in get_custom_layers
    raise Exception(f"Failed to parse ONNX file: {''.join(error_str)}")
Exception: Failed to parse ONNX file: In node -1 (importModel): INVALID_VALUE: Assertion failed: !mImporterCtx.network()->hasImplicitBatchDimension() && "This version of the ONNX parser only supports TensorRT INetworkDefinitions with an explicit batch dimension. Please ensure the network was created using the EXPLICIT_BATCH NetworkDefinitionCreationFlag."
```

The  modelopt  tool doesn't support  dynamic input batch , right?

Is there any method to quantize dynamic input batch model?

**Comment by demuxin** [comment]
I use static input shape  model to  quantize , but  there  is the same  error.

please give me some suggestion , thank you very much .

**Comment by demuxin** [comment]
I update onnx related python package to solve this error.
```
onnx                     1.17.0
onnx-graphsurgeon        0.5.2
onnxconverter-common     1.14.0
onnxmltools              1.12.0
onnxruntime              1.20.1
nvidia-modelopt          0.21.0
```

**Comment by Jepson-Song** [comment]
same question
