### ISSUE TITLE
[ONNX][PTQ] Quantization failed with --dq_only flag in ConvTranspose

### ISSUE THREAD

**Issue by ry3s** [NVIDIA/TensorRT-Model-Optimizer#117]
`qdq_to_dq()` function seems failed with QuantizeLinear of ConvTranspose weight.

## Environment
* Python: 3.10
* nvidia-modelopt: 0.21.0

<details>
<summary>pip freeze</summary>

```
annotated-types==0.7.0
cloudpickle==3.1.0
coloredlogs==15.0.1
cppimport==22.8.2
filelock==3.16.1
flatbuffers==24.3.25
humanfriendly==10.0
Mako==1.3.8
markdown-it-py==3.0.0
MarkupSafe==3.0.2
mdurl==0.1.2
mpmath==1.3.0
ninja==1.11.1.3
numpy==1.26.4
nvidia-modelopt==0.21.0
onnx==1.17.0
onnx-graphsurgeon==0.5.2
onnxconverter-common==1.14.0
onnxmltools==1.13.0
onnxruntime-gpu==1.18.1
packaging==24.2
protobuf==3.20.2
pybind11==2.13.6
pydantic==2.10.4
pydantic_core==2.27.2
Pygments==2.18.0
rich==13.9.4
scipy==1.14.1
sympy==1.13.3
tqdm==4.67.1
typing_extensions==4.12.2
```

</details>

## Reproduction steps

model: [`ctdet_coco_dlav0_384.onnx`](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/042_centernet)

```sh
python -m modelopt.onnx.quantization --onnx_path ctdet_coco_dlav0_384.onnx --output_path ctdet.int8.onnx --verbose --dq_only
```

<details>

<summary>console log</summary>

```
WARNING:root:No custom ops found. If that's not correct, please make sure that the 'tensorrt' python is correctly installed and that the path to 'libcudnn*.so' is in PATH or LD_LIBRARY_PATH. If the custom op is not directly available as a plugin in TensorRT, please also make sure that the path to the compiled '.so' TensorRT plugin is also being given via the '--trt_plugins' flag (requires TRT 10+).
INFO:root:Model ctdet_coco_dlav0_384.onnx with opset_version 9 is loaded.
INFO:root:Model is cloned to ctdet_coco_dlav0_384_opset13.onnx with opset_version 13.
INFO:root:Model is cloned to ctdet_coco_dlav0_384_named.onnx after naming the nodes.
INFO:root:Quantization Mode: int8
INFO:root:Quantizable op types in the model: ['ConvTranspose', 'MaxPool', 'Conv', 'BatchNormalization', 'Add']
INFO:root:Building non-residual Add input map ...
INFO:root:Searching for hard-coded patterns like MHA, LayerNorm, etc. to avoid quantization.
INFO:root:Building KGEN/CASK targeted partitions ...
INFO:root:CASK fusible partitions: [['Conv_1', 'BatchNormalization_1', 'Relu_1'], ['Conv_2', 'BatchNormalization_2', 'Relu_2'], ['Conv_3', 'BatchNormalization_3', 'Relu_3'], ['Conv_5', 'BatchNormalization_5', 'Relu_5'], ['Conv_4', 'BatchNormalization_4'], ['Conv_6', 'BatchNormalization_6', 'Add_6'], ['Conv_7', 'BatchNormalization_7', 'Relu_7'], ['Conv_8', 'BatchNormalization_8', 'Add_8'], ['Conv_9', 'BatchNormalization_9', 'Relu_9'], ['Conv_11', 'BatchNormalization_11', 'Relu_11'], ['Conv_10', 'BatchNormalization_10'], ['Conv_12', 'BatchNormalization_12', 'Add_12'], ['Conv_13', 'BatchNormalization_13', 'Relu_13'], ['Conv_14', 'BatchNormalization_14', 'Add_14'], ['Conv_15', 'BatchNormalization_15', 'Relu_15'], ['Conv_16', 'BatchNormalization_16', 'Relu_16'], ['Conv_17', 'BatchNormalization_17', 'Add_17'], ['Conv_18', 'BatchNormalization_18', 'Relu_18'], ['Conv_19', 'BatchNormalization_19', 'Add_19'], ['Conv_20', 'BatchNormalization_20', 'Relu_20'], ['Conv_22', 'BatchNormalization_22', 'Relu_22'], ['Conv_44', 'BatchNormalization_44', 'Relu_44'], ['Conv_21', 'BatchNormalization_21'], ['Conv_23', 'BatchNormalization_23', 'Add_23'], ['Conv_47', 'BatchNormalization_47', 'Relu_47'], ['Conv_24', 'BatchNormalization_24', 'Relu_24'], ['Conv_25', 'BatchNormalization_25', 'Add_25'], ['Conv_26', 'BatchNormalization_26', 'Relu_26'], ['Conv_27', 'BatchNormalization_27', 'Relu_27'], ['Conv_28', 'BatchNormalization_28', 'Add_28'], ['Conv_29', 'BatchNormalization_29', 'Relu_29'], ['Conv_30', 'BatchNormalization_30', 'Add_30'], ['Conv_31', 'BatchNormalization_31', 'Relu_31'], ['Conv_33', 'BatchNormalization_33', 'Relu_33'], ['Conv_40', 'BatchNormalization_40', 'Relu_40'], ['Conv_32', 'BatchNormalization_32'], ['Conv_34', 'BatchNormalization_34', 'Add_34'], ['Conv_42', 'BatchNormalization_42', 'Relu_42'], ['Conv_35', 'BatchNormalization_35', 'Relu_35'], ['Conv_45', 'BatchNormalization_45', 'Relu_45'], ['Conv_36', 'BatchNormalization_36', 'Add_36'], ['Conv_48', 'BatchNormalization_48', 'Relu_48'], ['Conv_37', 'BatchNormalization_37', 'Relu_37'], ['Conv_38', 'BatchNormalization_38', 'Relu_38'], ['Conv_39', 'BatchNormalization_39', 'Relu_39'], ['Conv_41', 'BatchNormalization_41', 'Relu_41'], ['Conv_43', 'BatchNormalization_43', 'Relu_43'], ['Conv_46', 'BatchNormalization_46', 'Relu_46'], ['Conv_49', 'BatchNormalization_49', 'Relu_49'], ['Conv_50', 'Relu_50'], ['Conv_52', 'Relu_52'], ['Conv_54', 'Relu_54'], ['Conv_51'], ['Conv_53'], ['Conv_55']]
INFO:root:KGEN partitions: []
INFO:root:Classifying the partition nodes ...
INFO:root:Total number of nodes: 188
INFO:root:Selected nodes to quantize: ['Conv_1', 'Conv_2', 'Conv_3', 'Conv_5', 'Conv_4', 'Conv_6', 'Conv_7', 'Conv_8', 'Conv_9', 'Conv_11', 'Conv_10', 'Conv_12', 'Conv_13', 'Conv_14', 'Conv_15', 'Conv_16', 'Conv_17', 'Conv_18', 'Conv_19', 'Conv_20', 'Conv_22', 'Conv_44', 'Conv_21', 'Conv_23', 'Conv_47', 'Conv_24', 'Conv_25', 'Conv_26', 'Conv_27', 'Conv_28', 'Conv_29', 'Conv_30', 'Conv_31', 'Conv_33', 'Conv_40', 'Conv_32', 'Conv_34', 'Conv_42', 'Conv_35', 'Conv_45', 'Conv_36', 'Conv_48', 'Conv_37', 'Conv_38', 'Conv_39', 'Conv_41', 'Conv_43', 'Conv_46', 'Conv_49', 'Conv_50', 'Conv_52', 'Conv_54', 'Conv_51', 'Conv_53', 'Conv_55', 'Add_6', 'Add_8', 'Add_12', 'Add_14', 'Add_17', 'Add_19', 'Add_23', 'Add_25', 'Add_28', 'Add_30', 'Add_34', 'Add_36', 'ConvTranspose_44', 'ConvTranspose_40', 'ConvTranspose_45', 'ConvTranspose_38', 'ConvTranspose_41', 'ConvTranspose_46', 'MaxPool_3', 'MaxPool_9', 'MaxPool_10', 'MaxPool_20', 'MaxPool_21', 'MaxPool_31']
WARNING:root:Please consider to run pre-processing before quantization. Refer to example: https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/ReadMe.md
2024-12-19 16:25:50.432387657 [E:onnxruntime:Default, provider_bridge_ort.cc:1731 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libcudnn.so.8: cannot open shared object file: No such file or directory

*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:456 void onnxruntime::python::RegisterTensorRTPluginsAsCustomOps(onnxruntime::python::PySessionOptions&, const ProviderOptions&) Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using [('CUDAExecutionProvider', {'device_id': 0}), 'CPUExecutionProvider', 'TensorrtExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-12-19 16:25:50.472261950 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

2024-12-19 16:25:50.472280037 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:895 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.
Collecting tensor data and making histogram ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 73/73 [00:00<00:00, 345.90it/s]
Finding optimal threshold for each tensor using 'entropy' algorithm ...
Number of tensors : 73
Number of histogram bins : 128 (The number may increase depends on the data it collects)
Number of quantized bins : 128
WARNING:root:Please consider pre-processing before quantization. See https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/ReadMe.md
INFO:root:Deleting QDQ nodes from marked inputs to make certain operations fusible ...
INFO:root:Processing base.base_layer.0.weight_QuantizeLinear
INFO:root:Processing base.level0.0.weight_QuantizeLinear
INFO:root:Processing base.level1.0.weight_QuantizeLinear
INFO:root:Processing base.level2.project.0.weight_QuantizeLinear
INFO:root:Processing base.level2.root.conv.weight_QuantizeLinear
INFO:root:Processing base.level2.tree1.conv1.weight_QuantizeLinear
INFO:root:Processing base.level2.tree1.conv2.weight_QuantizeLinear
INFO:root:Processing base.level2.tree2.conv1.weight_QuantizeLinear
INFO:root:Processing base.level2.tree2.conv2.weight_QuantizeLinear
INFO:root:Processing base.level3.tree1.project.0.weight_QuantizeLinear
INFO:root:Processing base.level3.tree1.root.conv.weight_QuantizeLinear
INFO:root:Processing base.level3.tree1.tree1.conv1.weight_QuantizeLinear
INFO:root:Processing base.level3.tree1.tree1.conv2.weight_QuantizeLinear
INFO:root:Processing base.level3.tree1.tree2.conv1.weight_QuantizeLinear
INFO:root:Processing base.level3.tree1.tree2.conv2.weight_QuantizeLinear
INFO:root:Processing base.level3.tree2.root.conv.weight_QuantizeLinear
INFO:root:Processing base.level3.tree2.tree1.conv1.weight_QuantizeLinear
INFO:root:Processing base.level3.tree2.tree1.conv2.weight_QuantizeLinear
INFO:root:Processing base.level3.tree2.tree2.conv1.weight_QuantizeLinear
INFO:root:Processing base.level3.tree2.tree2.conv2.weight_QuantizeLinear
INFO:root:Processing base.level4.tree1.project.0.weight_QuantizeLinear
INFO:root:Processing base.level4.tree1.root.conv.weight_QuantizeLinear
INFO:root:Processing base.level4.tree1.tree1.conv1.weight_QuantizeLinear
INFO:root:Processing base.level4.tree1.tree1.conv2.weight_QuantizeLinear
INFO:root:Processing base.level4.tree1.tree2.conv1.weight_QuantizeLinear
INFO:root:Processing base.level4.tree1.tree2.conv2.weight_QuantizeLinear
INFO:root:Processing base.level4.tree2.root.conv.weight_QuantizeLinear
INFO:root:Processing base.level4.tree2.tree1.conv1.weight_QuantizeLinear
INFO:root:Processing base.level4.tree2.tree1.conv2.weight_QuantizeLinear
INFO:root:Processing base.level4.tree2.tree2.conv1.weight_QuantizeLinear
INFO:root:Processing base.level4.tree2.tree2.conv2.weight_QuantizeLinear
INFO:root:Processing base.level5.project.0.weight_QuantizeLinear
INFO:root:Processing base.level5.root.conv.weight_QuantizeLinear
INFO:root:Processing base.level5.tree1.conv1.weight_QuantizeLinear
INFO:root:Processing base.level5.tree1.conv2.weight_QuantizeLinear
INFO:root:Processing base.level5.tree2.conv1.weight_QuantizeLinear
INFO:root:Processing base.level5.tree2.conv2.weight_QuantizeLinear
INFO:root:Processing dla_up.ida_0.node_1.0.weight_QuantizeLinear
INFO:root:Processing dla_up.ida_0.proj_1.0.weight_QuantizeLinear
INFO:root:Processing dla_up.ida_0.up_1.weight_QuantizeLinear
Traceback (most recent call last):
  File "/home/***/.asdf/installs/python/3.10.15/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/***/.asdf/installs/python/3.10.15/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/***/work/modelopt-bug/.venv/lib/python3.10/site-packages/modelopt/onnx/quantization/__main__.py", line 228, in <module>
    main()
  File "/home/***/work/modelopt-bug/.venv/lib/python3.10/site-packages/modelopt/onnx/quantization/__main__.py", line 201, in main
    quantize(
  File "/home/***/work/modelopt-bug/.venv/lib/python3.10/site-packages/modelopt/onnx/quantization/quantize.py", line 346, in quantize
    onnx_model = qdq_to_dq(onnx_model, verbose=verbose)
  File "/home/***/work/modelopt-bug/.venv/lib/python3.10/site-packages/modelopt/onnx/quantization/qdq_utils.py", line 574, in qdq_to_dq
    scale_init_idx, zp_init_idx = _convert(node)
  File "/home/***/work/modelopt-bug/.venv/lib/python3.10/site-packages/modelopt/onnx/quantization/qdq_utils.py", line 536, in _convert
    assert not np_y_scale.shape or w32.shape[-1] == np_y_scale.shape[0]
AssertionError
```

</details>

**Comment by i-riyad** [comment]
Can you try `modelopt==0.29.0`, this issue is fixed.

**Comment by i-riyad** [comment]
Reopen the issue if the problem persist with the latest modelopt.
