### ISSUE TITLE
how to quantize onnx to fp8?

### ISSUE THREAD

**Issue by yuvraj108c** [NVIDIA/TensorRT-Model-Optimizer#22]
Hi again,

I've successfully quantized an onnx model to int8, then converted to tensorrt engine and noticed the performance increase compared to fp16. 

```bash
python -m modelopt.onnx.quantization --onnx_path=model.onnx --quantize_mode=int8  --output_path=model.quant.onnx
```

Now I want to quantize the original onnx model to fp8, but it says I need to export my onnx with opset 19, which is unsupported using the following code. It tells me to use dynamo_export, but I cannot find any good documentation on it. Any help will be appreciated on how to export my model to fp8 onnx. Thanks.

```python
upscale_model = load_model("4x-UltraSharp.pth")

x = torch.rand(1, 3, 512, 512)

dynamic_axes = {
    "input": {0: "batch_size", 2: "width", 3: "height"},
    "output": {0: "batch_size", 2: "width", 3: "height"},
}
    
torch.onnx.export(upscale_model,
                    x,
                    "/workspace/ComfyUI/custom_nodes/ComfyUI-Upscaler-Tensorrt/ultrasharp.onnx",
                    verbose=True,
                    input_names=['input'],
                    output_names=['output'],
                    opset_version=19,
                    export_params=True,
                    dynamic_axes=dynamic_axes,
                    )
```

**Comment by i-riyad** [comment]
What is the error do you see when `--quantize_mode=fp8` is used? Please share the full stack trace along with the input ONNX model.

**Comment by yuvraj108c** [comment]
hmm, it worked now (i think so)
I cannot replicate the previous error where it says I need opset 19

However, the inference speed on the tensorrt engine is very slow with fp8 

```
python -m modelopt.onnx.quantization --onnx_path=4x-UltraSharp.onnx --quantize_mode=fp8  --output_path=model.quant.onnx
/workspace/ComfyUI/venv/lib/python3.10/site-packages/modelopt/onnx/quantization/int4.py:27: UserWarning: Using slower INT4 ONNX quantization using numpy. Install JAX (https://jax.readthedocs.io/en/latest/installation.html) for faster quantization: No module named 'jax'
  warnings.warn(
WARNING: No calibration data provided. Using random data for calibration.
INFO:root:Model 4x-UltraSharp.onnx with opset_version 17 is loaded.
INFO:root:Quantizable op types in the model: ['Conv']
INFO:root:Building non-residual Add input map ...
INFO:root:Searching for hard-coded patterns like MHA, LayerNorm, etc. to avoid quantization.
INFO:root:Building KGEN/CASK targeted partitions ...
INFO:root:Classifying the partition nodes ...
INFO:root:Found unpaddable conv for FP8: /model/model.0/Conv
INFO:root:Found unpaddable conv for FP8: /model/model.10/Conv
INFO:root:Total number of nodes: 1187
INFO:root:Skipped node count: 2
WARNING:root:Please consider to run pre-processing before quantization. Refer to example: https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/ReadMe.md 
/workspace/ComfyUI/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Collecting tensor data and making histogram ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 909/909 [00:00<00:00, 20906.09it/s]
Finding optimal threshold for each tensor using distribution algorithm ...
Number of tensors : 909
Number of histogram bins : 2048
Scenario : 'same')
/workspace/ComfyUI/venv/lib/python3.10/site-packages/onnxruntime/quantization/calibrate.py:861: RuntimeWarning: invalid value encountered in scalar power
  std = ((hist * values**2).sum() / hist.sum() - avg**2) ** 0.5
WARNING:root:Please consider pre-processing before quantization. See https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/ReadMe.md 
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[W] Could not convert: FLOAT8E4M3FN to a corresponding NumPy type. The original ONNX type will be preserved. 
INFO:root:Total number of quantized nodes: 420
INFO:root:Quantized node types: {'Conv', 'Add'}
INFO:root:Quantized onnx model is saved as model.quant.onnx
```
.pth: https://huggingface.co/Kim2091/UltraSharp/resolve/main/4x-UltraSharp.pth
.onnx (fp16, no model opt quantisation): https://huggingface.co/yuvraj108c/ComfyUI-Upscaler-Onnx/resolve/main/4x-UltraSharp.onnx

**Comment by yuvraj108c** [comment]
code for converting .onnx to .engine
Full code: https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/blob/master/utilities.py
```python
    def build(
        self,
        onnx_path,
        fp16,
        input_profile=None,
        enable_refit=False,
        enable_preview=False,
        enable_all_tactics=False,
        timing_cache=None,
        update_output_names=None,
    ):
        print(f"Building TensorRT engine for {onnx_path}: {self.engine_path}")
        p = [Profile()]
        if input_profile:
            p = [Profile() for i in range(len(input_profile))]
            for _p, i_profile in zip(p, input_profile):
                for name, dims in i_profile.items():
                    assert len(dims) == 3
                    _p.add(name, min=dims[0], opt=dims[1], max=dims[2])

        config_kwargs = {}
        if not enable_all_tactics:
            config_kwargs["tactic_sources"] = []

        network = network_from_onnx_path(
            onnx_path, flags=[trt.OnnxParserFlag.NATIVE_INSTANCENORM]
        )
        if update_output_names:
            print(f"Updating network outputs to {update_output_names}")
            network = ModifyNetworkOutputs(network, update_output_names)

        builder = network[0]
        config = builder.create_builder_config()
        config.progress_monitor = TQDMProgressMonitor()

        # config.set_flag(trt.BuilderFlag.FP16)
        config.set_flag(trt.BuilderFlag.FP8)
        config.set_flag(trt.BuilderFlag.REFIT) if enable_refit else None

        profiles = copy.deepcopy(p)
        for profile in profiles:
            # Last profile is used for set_calibration_profile.
            calib_profile = profile.fill_defaults(network[1]).to_trt(
                builder, network[1]
            )
            config.add_optimization_profile(calib_profile)

        try:
            engine = engine_from_network(
                network,
                config,
            )
        except Exception as e:
            error(f"Failed to build engine: {e}")
            return 1
        try:
            save_engine(engine, path=self.engine_path)
        except Exception as e:
            error(f"Failed to save engine: {e}")
            return 1
        return 0
```

**Comment by i-riyad** [comment]
We are working on this perf issue, stay tuned for the next modelopt release which will come around mid July.

**Comment by lix19937** [comment]
+1 watched

**Comment by yuvraj108c** [comment]
Any updates?

**Comment by i-riyad** [comment]
After internal debugging, we found that the perf issue is on the TensorRT side and the fix is in progress.

**Comment by WhiteTeaDragon** [comment]
Hello! Has this issue been resolved? Are there still performance issues?

**Comment by dkalog** [comment]
@yuvraj108c what is the hw on which you tried the fp8 ?

**Comment by yuvraj108c** [comment]
> [@yuvraj108c](https://github.com/yuvraj108c) what is the hw on which you tried the fp8 ?

i forgot, probably h100/rtx4090/l40s

**Comment by i-riyad** [comment]
With TensorRT 10.9, the performance gap for FP8 has been resolved. Please reopen the issue if the problem persists.

**Comment by vladlen32230** [comment]
## Not working

```bash
python -m modelopt.onnx.quantization --onnx_path=model.onnx --quantize_mode=fp8  --output_path=model.quant.onnx
[modelopt][onnx] - INFO - Starting quantization process for model: model.onnx
[modelopt][onnx] - INFO - Quantization mode: fp8
[modelopt][onnx] - INFO - Preprocessing the model model.onnx
[modelopt][onnx] - INFO - Model has dynamic inputs: ['input_ids', 'attention_mask']
[modelopt][onnx] - INFO - No custom ops found. If that's not correct, please make sure that the 'tensorrt' python package is correctly installed and that the paths to 'libcudnn*.so' and TensorRT 'lib/' are in 'LD_LIBRARY_PATH'. If the custom op is not directly available as a plugin in TensorRT, please also make sure that the path to the compiled '.so' TensorRT plugin is also being given via the  '--trt_plugins' flag (requires TRT 10+).
[modelopt][onnx] - INFO - Duplicating shared constants
[modelopt][onnx] - INFO - Initializing RandomDataProvider
[modelopt][onnx] - INFO - Generating random inputs for model
[modelopt][onnx] - INFO - Analyzing MHA nodes for fp8 quantization
[modelopt][onnx] - INFO - Creating ORT InferenceSession
[modelopt][onnx] - INFO - Checking for cuDNN library
[modelopt][onnx] - ERROR - cuDNN library not found in LD_LIBRARY_PATH
[modelopt][onnx] - WARNING - Failed to enable ORT with CUDA EP: 'libcudnn_adv*.so* is not accessible in LD_LIBRARY_PATH! Please make sure that the path to that library is in the env var to use the CUDA or TensorRT EP and ensure that the correct version is available. Versioning compatibility can be checked at https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements.'
[modelopt][onnx] - ERROR - Failed to import TensorRT >= 10.0
[modelopt][onnx] - WARNING - Failed to enable ORT with TensorRT EP: 'Could not import the `tensorrt` python package. Please install `tensorrt>=10.0` to use ORT's TensorRT Execution Provider. For more information on version compatibility, please check https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#requirements.'
[modelopt][onnx] - INFO - Successfully enabled 1 EPs for ORT: ['CPUExecutionProvider']
[modelopt][onnx] - INFO - Starting FP8 quantization process
[modelopt][onnx] - INFO - Loading ONNX model from model.onnx
[modelopt][onnx] - INFO - Configuring ORT for ModelOpt ONNX quantization
[modelopt][onnx] - INFO - Checking for cuDNN library
[modelopt][onnx] - ERROR - cuDNN library not found in LD_LIBRARY_PATH
[modelopt][onnx] - WARNING - Failed to enable ORT with CUDA EP: 'libcudnn_adv*.so* is not accessible in LD_LIBRARY_PATH! Please make sure that the path to that library is in the env var to use the CUDA or TensorRT EP and ensure that the correct version is available. Versioning compatibility can be checked at https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements.'
[modelopt][onnx] - ERROR - Failed to import TensorRT >= 10.0
[modelopt][onnx] - WARNING - Failed to enable ORT with TensorRT EP: 'Could not import the `tensorrt` python package. Please install `tensorrt>=10.0` to use ORT's TensorRT Execution Provider. For more information on version compatibility, please check https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#requirements.'
[modelopt][onnx] - INFO - Successfully enabled 1 EPs for ORT: ['CPUExecutionProvider']
[modelopt][onnx] - INFO - Quantizable op types in the model: ['Gemm', 'MatMul']
[modelopt][onnx] - INFO - Scanning for unsupported FP8 Conv nodes
[modelopt][onnx] - INFO - Found 0 unsupported FP8 Conv nodes
[modelopt][onnx] - INFO - Finding concat eliminated tensors
[modelopt][onnx] - INFO - Starting INT8 quantization with MinMax calibration
[modelopt][onnx] - INFO - Starting static quantization
unsupported broadcast between Min(8194, sequence_length) sequence_length
[modelopt][onnx] - INFO - Failed to infer shapes for model model.onnx: Incomplete symbolic shape inference
unsupported broadcast between Min(8194, sequence_length) sequence_length
[modelopt][onnx] - INFO - Failed to infer shapes for model model.onnx: Incomplete symbolic shape inference
2025-08-11 16:34:32.117422087 [W:onnxruntime:, graph.cc:4454 CleanUnusedInitializersAndNodeArgs] Removing initializer '338c92d8-14ce-46eb-9e6b-bf0d9c4f49ab'. It is not used by any node and should be removed from the model.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/slow_data_new/vladlen/fine_tuning/.venv4/lib/python3.10/site-packages/modelopt/onnx/quantization/__main__.py", line 288, in <module>
    main()
  File "/slow_data_new/vladlen/fine_tuning/.venv4/lib/python3.10/site-packages/modelopt/onnx/quantization/__main__.py", line 256, in main
    quantize(
  File "/slow_data_new/vladlen/fine_tuning/.venv4/lib/python3.10/site-packages/modelopt/onnx/quantization/quantize.py", line 402, in quantize
    onnx_model = quantize_func(
  File "/slow_data_new/vladlen/fine_tuning/.venv4/lib/python3.10/site-packages/modelopt/onnx/quantization/fp8.py", line 306, in quantize
    quantize_static(
  File "/slow_data_new/vladlen/fine_tuning/.venv4/lib/python3.10/site-packages/modelopt/onnx/quantization/ort_patching.py", line 1686, in _quantize_static
    quantizer.quantize_model()
  File "/slow_data_new/vladlen/fine_tuning/.venv4/lib/python3.10/site-packages/onnxruntime/quantization/qdq_quantizer.py", line 568, in quantize_model
    self._quantize_normal_tensors()
  File "/slow_data_new/vladlen/fine_tuning/.venv4/lib/python3.10/site-packages/onnxruntime/quantization/qdq_quantizer.py", line 978, in _quantize_normal_tensors
    raise ValueError(
ValueError: Quantization parameters are not specified for param /roberta/embeddings/LayerNorm/LayerNormalization_output_0. In static mode quantization params for inputs and outputs of nodes to be quantized are required.
```

## Onnx conversion script:

```bash
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import os
from shutil import copy2


class DisableCompileContextManager:
    def __init__(self):
        self._original_compile = torch.compile

    def __enter__(self):
        # Turn torch.compile into a no-op
        torch.compile = lambda *args, **kwargs: lambda x: x

    def __exit__(self, exc_type, exc_val, exc_tb):
        torch.compile = self._original_compile


def export():
    with DisableCompileContextManager():
        input_dir = "/slow_data_new/vladlen/fine_tuning/best_model_large_focused_bge"
        tokenizer = AutoTokenizer.from_pretrained(input_dir)
        model = AutoModelForSequenceClassification.from_pretrained(
            input_dir,
            num_labels=10,
            # Flash Attention 2.0's recalculated memory access pattern and partitioning strategy causes
            # onnx to report an error by not being able to compute the export map
            attn_implementation="eager", 
            # reference_compile=False, # disable triton compile
        )

        model.eval()

        samples = ['example']

        tokenized = tokenizer(samples,
                              return_tensors='pt',
                              max_length=tokenizer.model_max_length,
                              padding='max_length',
                              truncation=True)
        input_ids = tokenized['input_ids'].to('cuda')
        attention_mask = tokenized['attention_mask'].to('cuda')
        model = model.to('cuda')
        dir_to_save = 'chat_intent_detector_bge2/'
        os.makedirs(dir_to_save)
        with torch.no_grad():
            torch.onnx.export(
                model,
                (input_ids, attention_mask),
                dir_to_save + 'model.onnx',
                input_names=["input_ids", "attention_mask"],
                output_names=["logits"],
                export_params=True,
                dynamic_axes={'input_ids': {0: 'batch_size', 1: 'sequence_length'},
                              'attention_mask': {0: 'batch_size', 1: 'sequence_length'}},
                opset_version=19,
            )
            tokenizer.save_pretrained(dir_to_save)
            copy2(os.path.join(input_dir, 'config.json'), os.path.join(dir_to_save, 'config.json'))


if __name__ == '__main__':
    export()

```
