### ISSUE TITLE
Error when quantize Phi-3 to fp8, AssertionError: <class 'transformers.pytorch_utils.Conv1D'> already registered!

### ISSUE THREAD

**Issue by Ross-Fan** [NVIDIA/TensorRT-Model-Optimizer#24]
within the docker (IMAGE: nvidia/cuda:12.1.0-devel-ubuntu22.04)
GPU: A100 40GB
TensorRT-LLM version: 0.10.0
flash-attn    2.5.9.post1

I quantize the phi3 model(phi-3-medium-128k-instrcut/), with the following cmd:
scripts/huggingface_example.sh --type phi --model $HF_PATH --quant fp8 --tp 1

The error occur when  "python3 hf_ptq.py " in procedure
/usr/local/lib/python3.10/dist-packages/modelopt/torch/quantization/plugins/__init__.py:37: UserWarning: Failed to import diffusers plugin due to: RuntimeError('Failed to import transformers.models.falcon.modeling_falcon because of the following error (look up to see its traceback):\n/usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda14ExchangeDeviceEa')
  warnings.warn(f"Failed to import diffusers plugin due to: {repr(e)}")
/usr/local/lib/python3.10/dist-packages/modelopt/torch/quantization/plugins/__init__.py:44: UserWarning: Failed to import huggingface plugin due to: AssertionError("<class 'transformers.pytorch_utils.Conv1D'> already registered!")
  warnings.warn(f"Failed to import huggingface plugin due to: {repr(e)}")
Traceback (most recent call last):
  File "/home/tensorrt-model-optimizer/TensorRT-Model-Optimizer/llm_ptq/hf_ptq.py", line 32, in <module>
    import modelopt.torch.quantization as mtq
  File "/usr/local/lib/python3.10/dist-packages/modelopt/torch/__init__.py", line 13, in <module>
    from . import opt, quantization, sparsity, utils  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/modelopt/torch/quantization/__init__.py", line 13, in <module>
    from . import mode, plugins
  File "/usr/local/lib/python3.10/dist-packages/modelopt/torch/quantization/mode.py", line 25, in <module>
    from .conversion import (
  File "/usr/local/lib/python3.10/dist-packages/modelopt/torch/quantization/conversion.py", line 23, in <module>
    from .plugins.custom import register_custom_model_plugins_on_the_fly
  File "/usr/local/lib/python3.10/dist-packages/modelopt/torch/quantization/plugins/custom.py", line 25, in <module>
    from .huggingface import register_falcon_linears_on_the_fly
  File "/usr/local/lib/python3.10/dist-packages/modelopt/torch/quantization/plugins/huggingface.py", line 27, in <module>
    class _QuantConv1D(_QuantLinear):
  File "/usr/local/lib/python3.10/dist-packages/modelopt/torch/opt/dynamic.py", line 1001, in decorator
    assert nn_cls_ not in self._registry, f"{nn_cls_} already registered!"
AssertionError: <class 'transformers.pytorch_utils.Conv1D'> already registered!

Any solution on this Error?

**Comment by cjluo-nv** [comment]
The quantization error should be gone after the following release update, which will be out soon. With the next release, you should be able to quantize and generate the TRT LLM checkpoint. You may want to follow up with TRT LLM about when the Phi3 medium is supported.

**Comment by Ross-Fan** [comment]
> The quantization error should be gone after the following release update, which will be out soon. With the next release, you should be able to quantize and generate the TRT LLM checkpoint. You may want to follow up with TRT LLM about when the Phi3 medium is supported.

Thanks for your answer. As mentioned above, I checked the support model of trt-llm, the phi3-medium is not on the support list, so when would the trt-llm  support phi-3-medium-128k-instruct?

**Comment by cjluo-nv** [comment]
It might be supported soon in the main branch and the following TRT LLM official release

**Comment by kevalmorabia97** [comment]
Phi-3 should work with latest ModelOpt. Please reopen if you see issues
