### ISSUE TITLE
non-fatal error during eval

### ISSUE THREAD

**Issue by stas00** [NVIDIA/TensorRT-Model-Optimizer#82]
While running this example:
```
$ cd TensorRT-Model-Optimizer/llm_ptq
$ scripts/huggingface_example.sh --type llama --model $model --quant fp8 --tp 2
```

there was a non-fatal failure:

```
[8ad0971d422d:102499] Read -1, expected 4973, errno = 1
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 57/57 [06:28<00:00,  6.82s/it]
[TensorRT-LLM][INFO] Refreshed the MPI local session
[TensorRT-LLM][INFO] Refreshed the MPI local session
Exception in thread Thread-2 (stats_main):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/executor.py", line 755, in stats_main
    while (stats := self.mp_stats_queue.get()) is not None:
  File "/usr/local/lib/python3.10/dist-packages/modelopt/deploy/llm/generate.py", line 53, in _get
    obj = self.conn.recv()  # type: ignore[union-attr]
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 232: invalid start byte
```

I don't know if it's important to fix.

**Comment by cjluo-nv** [comment]
looks like a TRT LLM side issues. We will release a new version of modelopt combining TRTLLM 0.13 soon. We can revalidate it with the TRT LLM 0.13

**Comment by stas00** [comment]
sounds good, @cjluo-omniml 

FWIW, to me this looks like a borked dataset issue.
