### ISSUE TITLE
calib_dataloader created fail

### ISSUE THREAD

**Issue by relaxtheo** [NVIDIA/TensorRT-Model-Optimizer#91]
I am trying the vlm_ptq by following the readme in vlm_ptq folder, and when I call a command "scripts/huggingface_example.sh --type llava --model llava-1.5-7b-hf --quant fp8 --tp 8", (--deployment commented) following error message is reported:

Traceback (most recent call last):
  File "/WS/ModelOptWS/TensorRT-Model-Optimizer/vlm_ptq/../llm_ptq/hf_ptq.py", line 404, in <module>
    main(args)
  File "/WS/ModelOptWS/TensorRT-Model-Optimizer/vlm_ptq/../llm_ptq/hf_ptq.py", line 222, in main
    calib_dataloader = dataset_utils.get_dataset_dataloader(
  File "/WS/conda/envs/vlm_ptq/lib/python3.10/site-packages/modelopt/torch/utils/dataset_utils.py", line 124, in get_dataset_dataloader
    dataset = _get_dataset_samples(dataset_name, num_samples=num_samples)
  File "/WS/conda/envs/vlm_ptq/lib/python3.10/site-packages/modelopt/torch/utils/dataset_utils.py", line 65, in _get_dataset_samples
    dataset = load_dataset(
  File "/WS/conda/envs/vlm_ptq/lib/python3.10/site-packages/datasets/load.py", line 2076, in load_dataset
    builder_instance = load_dataset_builder(
  File "/WS/conda/envs/vlm_ptq/lib/python3.10/site-packages/datasets/load.py", line 1833, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
TypeError: 'NoneType' object is not callable

What's the problem for this issue? I have no idea for it, hope somebody can give some advice, thank you

**Comment by kevalmorabia97** [comment]
Have you tried re-running the update example with latest modelopt 0.19.0 to see if the issue persists?

**Comment by cjluo-nv** [comment]
This looks like a datasets issue. Have you tried upgrade the package?

**Comment by kevalmorabia97** [comment]
Closing as no further error reported. Feel free to reopen if issue persists
